name: arteria_fit_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.8.10+28

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  flutter_riverpod: ^3.3.1
  go_router: ^17.1.0
  animations: ^2.1.1
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  percent_indicator: ^4.2.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  vibration: ^3.1.8
  wakelock_plus: ^1.2.10
  flutter_native_splash: ^2.4.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  fl_chart: ^0.69.0
  share_plus: ^10.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/arteria-fit.png"
  min_sdk_android: 21
  adaptive_icon_background: "#F6F6F8"
  adaptive_icon_foreground: "assets/logo/arteria-fit.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#F6F6F8"
  color_dark: "#F6F6F8"
  image: assets/logo/arteria-fit.png
  android_12:
    image: assets/logo/arteria-fit.png
    color: "#F6F6F8"
    color_dark: "#F6F6F8"
    icon_background_color: "#F6F6F8"
    icon_background_color_dark: "#F6F6F8"
  ios: true
  web: false

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/recipes.json
    - assets/logo/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
